prefix = "."
stop-words = "stopwords.txt"

dataset = "train"
corpus = "line.toml"
index = "idx"
uninvert = true # create the forward index by un-inverting the
                # inverted index; can save some processing time
                # when using both indexes

[[analyzers]]
method = "ngram-word"
ngram = 1
# filter = "default-unigram-chain"
filter = [{type = "icu-tokenizer"}, {type = "lowercase"}]
# filter = [{type = "icu-tokenizer", suppress-tags = true}, {type = "lowercase"}]
